{{- if and .Values.agent.enabled (eq .Values.agent.kind "StatefulSet") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gocd.fullname" . }}-agent
  labels:
    app: {{ template "gocd.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    component: agent
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 8152
      targetPort: 8152
  selector:
    app: {{ template "gocd.name" . }}
    release: {{ .Release.Name | quote }}
    component: agent
{{- end }}
