name: Lint and Test Charts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s: # See https://hub.docker.com/r/kindest/node/tags and https://endoflife.date/kubernetes
          - v1.21.14 # EOL 2022-06-28
          - v1.22.15 # EOL 2022-10-28
          - v1.23.13 # EOL 2023-02-28
          - v1.24.7  # EOL 2023-07-28
          - v1.25.3  # EOL 2023-10-27
          - v1.26.0  # EOL 2024-02-28
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.10.3 # See https://github.com/helm/helm/releases

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
        # Only build a kind cluster if there are chart changes to test.
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config .github/ct.yaml
