name: Lint and Test Charts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s: # See https://hub.docker.com/r/kindest/node/tags for valid tags
          # For relevant EOLs https://endoflife.date/kubernetes / https://endoflife.date/amazon-eks / https://endoflife.date/azure-kubernetes-service / https://endoflife.date/google-kubernetes-engine
          - v1.23.17 # EOL 2023-02-28 (latest 2023-10-11 for EKS)
          - v1.24.15 # EOL 2023-07-28 (latest 2024-01-31 for EKS)
          - v1.25.11 # EOL 2023-10-27 (latest 2024-05-07 for EKS)
          - v1.26.6  # EOL 2024-02-28 (latest 2024-06-01 for EKS)
          - v1.27.3  # EOL 2024-06-28 (latest 2024-08-24 for GKE)
          - v1.28.0  # EOL 2024-10-28 (latest 2024-11-01 for EKS)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
        # Only build a kind cluster if there are chart changes to test.
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config .github/ct.yaml
