name: Release Charts

on:
  workflow_run:
    workflows: [Lint and Test Charts]
    branches: [master]
    types: [completed]
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v2.0
        with:
          version: v3.8.0

      - name: Run chart-releaser
        # Change version back for 1.2.2+ - see https://github.com/helm/chart-releaser-action/pull/83
        uses: helm/chart-releaser-action@main
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
